version: '3.8'

services:
  shorturl:
    build: ./
    command: go run . memory
    ports:
      - '80:8090'
    depends_on:
      - db
    environment:
      - DB_PASSWORD=1
  db:
    restart: always
    image: postgres:latest
    environment:
      - POSTGRES_DB=short
      - POSTGRES_PASSWORD=1
      - POSTGRES_USER=postgres
    ports:
      - '5436:5432'